In [273]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)
from random import randint
from sklearn.utils import shuffle 
from sklearn.preprocessing import MinMaxScaler

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-data/irisdata.csv


In [274]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.metrics import categorical_crossentropy

In [275]:
iris_train = pd.read_csv("../input/iris-data/irisdata.csv", header = 0, names = ["sepal_length","sepal_width","petal_length","petal_width","species"])
iris_train['species'] = np.where(iris_train['species'] == 'setosa', 0.0, iris_train['species'])
iris_train['species'] = np.where(iris_train['species'] == 'versicolor', 1.0, iris_train['species'])
iris_train['species'] = np.where(iris_train['species'] == 'virginica', 2.0, iris_train['species'])
iris_train['species'] = np.asarray(iris_train['species']).astype('float32')
iris_train.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2      0.0
1           4.9          3.0           1.4          0.2      0.0
2           4.7          3.2           1.3          0.2      0.0
3           4.6          3.1           1.5          0.2      0.0
4           5.0          3.6           1.4          0.2      0.0

In [276]:
iris_features = iris_train.copy()
#iris_features['species'] = np.where(iris_features['species'] == 'setosa', 0.0, iris_features['species'])
#iris_features['species'] = np.where(iris_features['species'] == 'versicolor', 1.0, iris_features['species'])
#iris_features['species'] = np.where(iris_features['species'] == 'virginica', 2.0, iris_features['species'])
iris_labels = iris_features.pop('species')


In [277]:
iris_features = np.array(iris_features)
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [278]:
#normalize = preprocessing.Normalization()

#normalize.adapt(iris_features)
scaler = MinMaxScaler(feature_range=(0,1))
iris_features = scaler.fit_transform(iris_features.reshape(-4,4))
iris_features

array([[0.222, 0.625, 0.068, 0.042],
       [0.167, 0.417, 0.068, 0.042],
       [0.111, 0.5  , 0.051, 0.042],
       [0.083, 0.458, 0.085, 0.042],
       [0.194, 0.667, 0.068, 0.042],
       [0.306, 0.792, 0.119, 0.125],
       [0.083, 0.583, 0.068, 0.083],
       [0.194, 0.583, 0.085, 0.042],
       [0.028, 0.375, 0.068, 0.042],
       [0.167, 0.458, 0.085, 0.   ],
       [0.306, 0.708, 0.085, 0.042],
       [0.139, 0.583, 0.102, 0.042],
       [0.139, 0.417, 0.068, 0.   ],
       [0.   , 0.417, 0.017, 0.   ],
       [0.417, 0.833, 0.034, 0.042],
       [0.389, 1.   , 0.085, 0.125],
       [0.306, 0.792, 0.051, 0.125],
       [0.222, 0.625, 0.068, 0.083],
       [0.389, 0.75 , 0.119, 0.083],
       [0.222, 0.75 , 0.085, 0.083],
       [0.306, 0.583, 0.119, 0.042],
       [0.222, 0.708, 0.085, 0.125],
       [0.083, 0.667, 0.   , 0.042],
       [0.222, 0.542, 0.119, 0.167],
       [0.139, 0.583, 0.153, 0.042],
       [0.194, 0.417, 0.102, 0.042],
       [0.194, 0.583, 0.102, 0.125],
 

In [279]:
#iris_labels, iris_features = shuffle(iris_labels,iris_features)
#iris_features

array([[0.167, 0.458, 0.085, 0.   ],
       [0.722, 0.5  , 0.797, 0.917],
       [0.333, 0.167, 0.475, 0.417],
       [0.444, 0.417, 0.542, 0.583],
       [0.194, 0.625, 0.102, 0.208],
       [0.722, 0.458, 0.695, 0.917],
       [0.   , 0.417, 0.017, 0.   ],
       [0.167, 0.167, 0.39 , 0.375],
       [0.5  , 0.375, 0.627, 0.542],
       [0.25 , 0.583, 0.068, 0.042],
       [0.194, 0.542, 0.068, 0.042],
       [0.556, 0.542, 0.627, 0.625],
       [0.417, 0.833, 0.034, 0.042],
       [0.417, 0.333, 0.695, 0.958],
       [0.306, 0.708, 0.085, 0.042],
       [0.472, 0.417, 0.644, 0.708],
       [0.611, 0.417, 0.712, 0.792],
       [0.194, 0.5  , 0.034, 0.042],
       [0.361, 0.417, 0.525, 0.5  ],
       [0.722, 0.458, 0.746, 0.833],
       [0.028, 0.375, 0.068, 0.042],
       [0.361, 0.375, 0.441, 0.5  ],
       [0.194, 0.417, 0.102, 0.042],
       [0.722, 0.458, 0.661, 0.583],
       [0.917, 0.417, 0.949, 0.833],
       [0.194, 0.583, 0.085, 0.042],
       [0.583, 0.5  , 0.729, 0.917],
 

In [280]:
model = Sequential([
    Dense(units = 18, input_shape = (10,4), activation = 'relu'),
    Dense(units = 36, activation = 'relu'),
    Dense(units = 3, activation = 'softmax')
])

In [281]:
model.summary()

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_66 (Dense)             (None, 10, 18)            90        
_________________________________________________________________
dense_67 (Dense)             (None, 10, 36)            684       
_________________________________________________________________
dense_68 (Dense)             (None, 10, 3)             111       
Total params: 885
Trainable params: 885
Non-trainable params: 0
_________________________________________________________________


In [282]:
model.compile(optimizer=SGD(learning_rate = 0.05), loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [283]:
model.fit(x = iris_features, y = iris_labels, validation_split = 0.1, batch_size = 10, epochs = 50, shuffle = True, verbose = 2)

Epoch 1/50
14/14 - 0s - loss: 1.1181 - accuracy: 0.2741 - val_loss: 1.0566 - val_accuracy: 0.1333
Epoch 2/50
14/14 - 0s - loss: 0.9939 - accuracy: 0.5333 - val_loss: 0.9705 - val_accuracy: 0.6000
Epoch 3/50
14/14 - 0s - loss: 0.9063 - accuracy: 0.6741 - val_loss: 0.9097 - val_accuracy: 0.6000
Epoch 4/50
14/14 - 0s - loss: 0.8281 - accuracy: 0.6741 - val_loss: 0.8297 - val_accuracy: 0.6000
Epoch 5/50
14/14 - 0s - loss: 0.7479 - accuracy: 0.6741 - val_loss: 0.7341 - val_accuracy: 0.6000
Epoch 6/50
14/14 - 0s - loss: 0.6756 - accuracy: 0.6741 - val_loss: 0.6627 - val_accuracy: 0.6000
Epoch 7/50
14/14 - 0s - loss: 0.6127 - accuracy: 0.6741 - val_loss: 0.6190 - val_accuracy: 0.6000
Epoch 8/50
14/14 - 0s - loss: 0.5629 - accuracy: 0.6741 - val_loss: 0.5395 - val_accuracy: 0.6667
Epoch 9/50
14/14 - 0s - loss: 0.5252 - accuracy: 0.7407 - val_loss: 0.5113 - val_accuracy: 0.6000
Epoch 10/50
14/14 - 0s - loss: 0.4949 - accuracy: 0.7111 - val_loss: 0.4859 - val_accuracy: 0.6667
Epoch 11/50
14/14 -

In [284]:
from sklearn.cluster import KMeans 
# 3 clusters 
n_clusters = 3 
 
kmeans = KMeans(n_clusters=n_clusters, init = 'k-means++', n_init=20, verbose = 2) 
# Train K-Means. 
kmeans.fit(X = iris_features) 
kmeans.fit_predict(X = iris_features)


Initialization complete
Iteration 0, inertia 13.195552255010437
Iteration 1, inertia 8.29030970171904
Iteration 2, inertia 7.185605759583683
Iteration 3, inertia 7.171076175217029
Iteration 4, inertia 7.127335193386674
Iteration 5, inertia 7.1012962366573
Iteration 6, inertia 7.073223815410934
Iteration 7, inertia 7.026519352854868
Iteration 8, inertia 7.001592023801331
Iteration 9, inertia 6.9981140048267605
Converged at iteration 9: strict convergence.
Initialization complete
Iteration 0, inertia 11.95006429302279
Iteration 1, inertia 7.2212217657741835
Iteration 2, inertia 7.0537882659539095
Iteration 3, inertia 7.003317600098681
Iteration 4, inertia 6.9981140048267605
Converged at iteration 4: strict convergence.
Initialization complete
Iteration 0, inertia 11.421843967339456
Iteration 1, inertia 7.0537882659539095
Iteration 2, inertia 7.003317600098681
Iteration 3, inertia 6.9981140048267605
Converged at iteration 3: strict convergence.
Initialization complete
Iteration 0, inertia

Iteration 3, inertia 7.073931926882712
Iteration 4, inertia 7.003317600098681
Iteration 5, inertia 6.9981140048267605
Converged at iteration 5: strict convergence.
Initialization complete
Iteration 0, inertia 10.35510601421828
Iteration 1, inertia 7.5009268267426386
Iteration 2, inertia 7.26678438443353
Iteration 3, inertia 7.206573917663919
Iteration 4, inertia 7.193121890494896
Iteration 5, inertia 7.182667132756729
Iteration 6, inertia 7.169111467307472
Iteration 7, inertia 7.151593675022102
Iteration 8, inertia 7.138647703985378
Converged at iteration 8: strict convergence.
Initialization complete
Iteration 0, inertia 9.14007339445881
Iteration 1, inertia 7.1439601432801
Iteration 2, inertia 7.110841102457291
Iteration 3, inertia 7.073223815410934
Iteration 4, inertia 7.026519352854868
Iteration 5, inertia 7.001592023801331
Iteration 6, inertia 6.9981140048267605
Converged at iteration 6: strict convergence.
Initialization complete
Iteration 0, inertia 8.359052759069515
Iteration 1

array([1, 2, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 1, 0, 2, 1, 0,
       1, 2, 2, 1, 2, 1, 2, 0, 0, 2, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 2,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0,
       1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 2, 1,
       1, 2, 1, 0, 0, 1, 1, 1, 0, 1, 2, 2, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0,
       1, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 2, 0, 2, 2, 2, 1,
       2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0], dtype=int32)

In [285]:
model.save('iris_dataset.model')