In [312]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)
from random import randint
from sklearn.utils import shuffle 
from sklearn.preprocessing import MinMaxScaler

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-data/irisdata.csv


In [313]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.metrics import categorical_crossentropy

In [314]:
iris_train = pd.read_csv("../input/iris-data/irisdata.csv", header = 0, names = ["sepal_length","sepal_width","petal_length","petal_width","species"])
iris_train['species'] = np.where(iris_train['species'] == 'setosa', 0.0, iris_train['species'])
iris_train['species'] = np.where(iris_train['species'] == 'versicolor', 1.0, iris_train['species'])
iris_train['species'] = np.where(iris_train['species'] == 'virginica', 2.0, iris_train['species'])
iris_train['species'] = np.asarray(iris_train['species']).astype('float32')
iris_train.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2      0.0
1           4.9          3.0           1.4          0.2      0.0
2           4.7          3.2           1.3          0.2      0.0
3           4.6          3.1           1.5          0.2      0.0
4           5.0          3.6           1.4          0.2      0.0

In [315]:
iris_features = iris_train.copy()
#iris_features['species'] = np.where(iris_features['species'] == 'setosa', 0.0, iris_features['species'])
#iris_features['species'] = np.where(iris_features['species'] == 'versicolor', 1.0, iris_features['species'])
#iris_features['species'] = np.where(iris_features['species'] == 'virginica', 2.0, iris_features['species'])
iris_labels = iris_features.pop('species')


In [316]:
iris_features = np.array(iris_features)
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [317]:
#normalize = preprocessing.Normalization()

#normalize.adapt(iris_features)
#scaler = MinMaxScaler(feature_range=(0,1))
#iris_features = scaler.fit_transform(iris_features.reshape(-4,4))
#iris_features

array([[0.222, 0.625, 0.068, 0.042],
       [0.167, 0.417, 0.068, 0.042],
       [0.111, 0.5  , 0.051, 0.042],
       [0.083, 0.458, 0.085, 0.042],
       [0.194, 0.667, 0.068, 0.042],
       [0.306, 0.792, 0.119, 0.125],
       [0.083, 0.583, 0.068, 0.083],
       [0.194, 0.583, 0.085, 0.042],
       [0.028, 0.375, 0.068, 0.042],
       [0.167, 0.458, 0.085, 0.   ],
       [0.306, 0.708, 0.085, 0.042],
       [0.139, 0.583, 0.102, 0.042],
       [0.139, 0.417, 0.068, 0.   ],
       [0.   , 0.417, 0.017, 0.   ],
       [0.417, 0.833, 0.034, 0.042],
       [0.389, 1.   , 0.085, 0.125],
       [0.306, 0.792, 0.051, 0.125],
       [0.222, 0.625, 0.068, 0.083],
       [0.389, 0.75 , 0.119, 0.083],
       [0.222, 0.75 , 0.085, 0.083],
       [0.306, 0.583, 0.119, 0.042],
       [0.222, 0.708, 0.085, 0.125],
       [0.083, 0.667, 0.   , 0.042],
       [0.222, 0.542, 0.119, 0.167],
       [0.139, 0.583, 0.153, 0.042],
       [0.194, 0.417, 0.102, 0.042],
       [0.194, 0.583, 0.102, 0.125],
 

In [318]:
#iris_labels, iris_features = shuffle(iris_labels,iris_features)
#iris_features

In [319]:
model = Sequential([
    Dense(units = 18, input_shape = (10,4), activation = 'relu'),
    Dense(units = 36, activation = 'relu'),
    Dense(units = 3, activation = 'softmax')
])

In [320]:
model.summary()

Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_75 (Dense)             (None, 10, 18)            90        
_________________________________________________________________
dense_76 (Dense)             (None, 10, 36)            684       
_________________________________________________________________
dense_77 (Dense)             (None, 10, 3)             111       
Total params: 885
Trainable params: 885
Non-trainable params: 0
_________________________________________________________________


In [321]:
model.compile(optimizer=SGD(learning_rate = 0.05), loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [322]:
model.fit(x = iris_features, y = iris_labels, validation_split = 0.1, batch_size = 10, epochs = 50, shuffle = True, verbose = 2)

Epoch 1/50
14/14 - 0s - loss: 0.9980 - accuracy: 0.5259 - val_loss: 0.9475 - val_accuracy: 0.0000e+00
Epoch 2/50
14/14 - 0s - loss: 0.9065 - accuracy: 0.7259 - val_loss: 0.8810 - val_accuracy: 0.0000e+00
Epoch 3/50
14/14 - 0s - loss: 0.8215 - accuracy: 0.7778 - val_loss: 0.9285 - val_accuracy: 0.0000e+00
Epoch 4/50
14/14 - 0s - loss: 0.7435 - accuracy: 0.7407 - val_loss: 0.7782 - val_accuracy: 0.4667
Epoch 5/50
14/14 - 0s - loss: 0.6708 - accuracy: 0.8519 - val_loss: 0.7240 - val_accuracy: 0.7333
Epoch 6/50
14/14 - 0s - loss: 0.6054 - accuracy: 0.8741 - val_loss: 0.6309 - val_accuracy: 1.0000
Epoch 7/50
14/14 - 0s - loss: 0.5500 - accuracy: 0.9037 - val_loss: 0.7821 - val_accuracy: 0.0667
Epoch 8/50
14/14 - 0s - loss: 0.5115 - accuracy: 0.8963 - val_loss: 0.5792 - val_accuracy: 1.0000
Epoch 9/50
14/14 - 0s - loss: 0.4728 - accuracy: 0.9111 - val_loss: 0.5274 - val_accuracy: 1.0000
Epoch 10/50
14/14 - 0s - loss: 0.4402 - accuracy: 0.8963 - val_loss: 0.5625 - val_accuracy: 0.8667
Epoch 1

In [323]:
from sklearn.cluster import KMeans 
# 3 clusters 
n_clusters = 3 
 
kmeans = KMeans(n_clusters=n_clusters, init = 'k-means++', n_init=20, verbose = 2) 
# Train K-Means. 
kmeans.fit(X = iris_features) 
kmeans.fit_predict(X = iris_features)


Initialization complete
Iteration 0, inertia 12.911406464457851
Iteration 1, inertia 7.415729003742208
Iteration 2, inertia 7.046428872390634
Iteration 3, inertia 7.001592023801327
Iteration 4, inertia 6.9981140048267605
Converged at iteration 4: strict convergence.
Initialization complete
Iteration 0, inertia 8.08596407171559
Iteration 1, inertia 7.098350804884603
Iteration 2, inertia 7.016263174302656
Iteration 3, inertia 6.9981140048267605
Converged at iteration 3: strict convergence.
Initialization complete
Iteration 0, inertia 15.247800892676633
Iteration 1, inertia 7.462546803673117
Iteration 2, inertia 7.266784384433528
Iteration 3, inertia 7.20657391766392
Iteration 4, inertia 7.193121890494894
Iteration 5, inertia 7.182667132756725
Iteration 6, inertia 7.169111467307468
Iteration 7, inertia 7.151593675022098
Iteration 8, inertia 7.138647703985377
Converged at iteration 8: strict convergence.
Initialization complete
Iteration 0, inertia 10.76969443469132
Iteration 1, inertia 7.

Iteration 1, inertia 7.859023312953088
Iteration 2, inertia 7.389999990808192
Iteration 3, inertia 7.232621438200393
Iteration 4, inertia 7.200448847514463
Iteration 5, inertia 7.182667132756725
Iteration 6, inertia 7.169111467307468
Iteration 7, inertia 7.151593675022098
Iteration 8, inertia 7.138647703985377
Converged at iteration 8: strict convergence.
Initialization complete
Iteration 0, inertia 9.209098122169376
Iteration 1, inertia 7.212642829114388
Iteration 2, inertia 7.053788265953908
Iteration 3, inertia 7.003317600098681
Iteration 4, inertia 6.9981140048267605
Converged at iteration 4: strict convergence.
Initialization complete
Iteration 0, inertia 9.342489907735462
Iteration 1, inertia 7.171883337095208
Iteration 2, inertia 7.101296236657297
Iteration 3, inertia 7.073223815410932
Iteration 4, inertia 7.026519352854868
Iteration 5, inertia 7.001592023801327
Iteration 6, inertia 6.9981140048267605
Converged at iteration 6: strict convergence.
Initialization complete
Iteratio

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1], dtype=int32)

In [324]:
model.save('iris_dataset.model')