In [88]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)
from random import randint
from sklearn.utils import shuffle 
from sklearn.preprocessing import MinMaxScaler

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-data/irisdata.csv


In [89]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.metrics import categorical_crossentropy

In [90]:
iris_train = pd.read_csv("../input/iris-data/irisdata.csv", header = 0, names = ["sepal_length","sepal_width","petal_length","petal_width","species"])
iris_train['species'] = np.where(iris_train['species'] == 'setosa', 0.0, iris_train['species'])
iris_train['species'] = np.where(iris_train['species'] == 'versicolor', 1.0, iris_train['species'])
iris_train['species'] = np.where(iris_train['species'] == 'virginica', 2.0, iris_train['species'])
iris_train['species'] = np.asarray(iris_train['species']).astype('float32')
iris_train.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2      0.0
1           4.9          3.0           1.4          0.2      0.0
2           4.7          3.2           1.3          0.2      0.0
3           4.6          3.1           1.5          0.2      0.0
4           5.0          3.6           1.4          0.2      0.0

In [91]:
iris_features = iris_train.copy()
#iris_features['species'] = np.where(iris_features['species'] == 'setosa', 0.0, iris_features['species'])
#iris_features['species'] = np.where(iris_features['species'] == 'versicolor', 1.0, iris_features['species'])
#iris_features['species'] = np.where(iris_features['species'] == 'virginica', 2.0, iris_features['species'])
iris_labels = iris_features.pop('species')


In [92]:
iris_features = np.array(iris_features)
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [93]:
#normalize = preprocessing.Normalization()

#normalize.adapt(iris_features)
scaler = MinMaxScaler(feature_range=(0,1))
iris_features = scaler.fit_transform(iris_features.reshape(-4,4))
iris_features

array([[0.222, 0.625, 0.068, 0.042],
       [0.167, 0.417, 0.068, 0.042],
       [0.111, 0.5  , 0.051, 0.042],
       [0.083, 0.458, 0.085, 0.042],
       [0.194, 0.667, 0.068, 0.042],
       [0.306, 0.792, 0.119, 0.125],
       [0.083, 0.583, 0.068, 0.083],
       [0.194, 0.583, 0.085, 0.042],
       [0.028, 0.375, 0.068, 0.042],
       [0.167, 0.458, 0.085, 0.   ],
       [0.306, 0.708, 0.085, 0.042],
       [0.139, 0.583, 0.102, 0.042],
       [0.139, 0.417, 0.068, 0.   ],
       [0.   , 0.417, 0.017, 0.   ],
       [0.417, 0.833, 0.034, 0.042],
       [0.389, 1.   , 0.085, 0.125],
       [0.306, 0.792, 0.051, 0.125],
       [0.222, 0.625, 0.068, 0.083],
       [0.389, 0.75 , 0.119, 0.083],
       [0.222, 0.75 , 0.085, 0.083],
       [0.306, 0.583, 0.119, 0.042],
       [0.222, 0.708, 0.085, 0.125],
       [0.083, 0.667, 0.   , 0.042],
       [0.222, 0.542, 0.119, 0.167],
       [0.139, 0.583, 0.153, 0.042],
       [0.194, 0.417, 0.102, 0.042],
       [0.194, 0.583, 0.102, 0.125],
 

In [94]:
iris_labels, iris_features = shuffle(iris_labels,iris_features)
iris_features

array([[0.556, 0.333, 0.695, 0.583],
       [0.639, 0.375, 0.61 , 0.5  ],
       [0.333, 0.917, 0.068, 0.042],
       [0.5  , 0.333, 0.508, 0.5  ],
       [0.722, 0.458, 0.695, 0.917],
       [0.944, 0.417, 0.864, 0.917],
       [0.917, 0.417, 0.949, 0.833],
       [0.417, 0.833, 0.034, 0.042],
       [0.194, 0.583, 0.102, 0.125],
       [0.139, 0.417, 0.068, 0.   ],
       [0.306, 0.792, 0.119, 0.125],
       [0.139, 0.583, 0.153, 0.042],
       [0.472, 0.083, 0.678, 0.583],
       [0.306, 0.583, 0.119, 0.042],
       [0.667, 0.542, 0.797, 1.   ],
       [0.944, 0.333, 0.966, 0.792],
       [0.222, 0.625, 0.068, 0.083],
       [0.194, 0.625, 0.102, 0.208],
       [0.139, 0.458, 0.102, 0.042],
       [0.694, 0.5  , 0.831, 0.917],
       [0.028, 0.5  , 0.051, 0.042],
       [0.   , 0.417, 0.017, 0.   ],
       [1.   , 0.75 , 0.915, 0.792],
       [0.472, 0.417, 0.644, 0.708],
       [0.944, 0.75 , 0.966, 0.875],
       [0.583, 0.458, 0.763, 0.708],
       [0.861, 0.333, 0.864, 0.75 ],
 

In [95]:
model = Sequential([
    Dense(units = 18, input_shape = (10,4), activation = 'relu'),
    Dense(units = 36, activation = 'relu'),
    Dense(units = 3, activation = 'softmax')
])

In [96]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 10, 18)            90        
_________________________________________________________________
dense_19 (Dense)             (None, 10, 36)            684       
_________________________________________________________________
dense_20 (Dense)             (None, 10, 3)             111       
Total params: 885
Trainable params: 885
Non-trainable params: 0
_________________________________________________________________


In [97]:
model.compile(optimizer=SGD(learning_rate = 0.05), loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [98]:
model.fit(x = iris_features, y = iris_labels, validation_split = 0.1, batch_size = 10, epochs = 50, shuffle = True, verbose = 2)

SyntaxError: invalid syntax (<ipython-input-98-3f2c5a409e41>, line 1)

In [ ]:
model.save('iris_dataset.model')